version: '3.2'
services:
  code-challenge_reactapptest:
    build:
      context: .
      dockerfile: /Users/phillipdacosta/code-challenge/Dockerfile
  cypress:
    image: "cypress/included:4.4.0"
    restart: on-failure
    depends_on:
      - code-challenge_reactapptest
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
    working_dir: /e2e
    volumes:
      - ./:/e2e