version: '3.2'
services:
  code-challenge_reactapptest:
    build: .
    ports:
      - "8080:3000"
  cypress:
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
    image: "cypress/included:4.4.0"
    restart: on-failure
    depends_on:
      - code-challenge_reactapptest
    environment:
      - CYPRESS_baseUrl=http://0.0.0.0:8080/
    working_dir: /e2e
    volumes:
      - ./:/e2e
    command: >
      /bin/bash -c "
        while ! nc -z web 8080;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
      "  