language: node_js
node_js:
  - "7"
env:
  - NODE_ENV=travis
branches:
  only:
    - master
cache:
  directories:
    - node_modules
services:
  - docker
notifications:
  email:
      - phillip.dacosta@gmail.com
install:
 - npm install
 - docker-compose up

before_install:
 - "source <(curl -H 'Authorization: token '$GIT_USER_TOKEN'' -L https://raw.githubusercontent.com/alokadhao20/testCI01/master/before_install_setup.sh)"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true

  on:
    branch: master 