language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
before_script:
  - npm install
+ script:
+   - npm test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true

  on:
    branch: master  